import { AGENT_VERSION, APP_VERSION } from "./_core/systemRouter";

/**
 * 生成 Go Agent 一键安装脚本（自包含，不依赖 Shell Agent）。
 *
 * 用法：
 *   curl -sL PANEL_URL/api/agent/install.sh | bash -s -- install YOUR_TOKEN
 *   curl -sL PANEL_URL/api/agent/install.sh | bash -s -- upgrade
 *   curl -sL PANEL_URL/api/agent/install.sh | bash -s -- uninstall
 *
 * @param defaultPanelUrl 面板地址（当用户未通过 PANEL_URL 环境变量指定时使用）
 * @param token 可选，预嵌入 Token；未提供时从命令行参数读取
 */
export function generateInstallScript(defaultPanelUrl: string, token?: string): string {
  const embeddedToken = token || "";
  const lines = [
    '#!/bin/bash',
    '# ForwardX Agent (Go) 一键安装/管理脚本',
    '# 安装: curl -sL PANEL_URL/api/agent/install.sh | bash -s -- install YOUR_TOKEN',
    '# 升级: curl -sL PANEL_URL/api/agent/install.sh | bash -s -- upgrade',
    '# 卸载: curl -sL PANEL_URL/api/agent/install.sh | bash -s -- uninstall',
    '',
    'set -e',
    '',
    'ACTION="${1:-${ACTION:-}}"',
    'TOKEN="${2:-${TOKEN:-}}"',
    // 优先使用环境变量 PANEL_URL，其次使用脚本嵌入的默认值
    `PANEL_URL="\${PANEL_URL:-${defaultPanelUrl}}"`,
    `AGENT_VERSION="${AGENT_VERSION}"`,
    `RELEASE_VERSION="${APP_VERSION}"`,
    'EMBEDDED_TOKEN="' + embeddedToken + '"',
    '',
    'GO_AGENT_BIN="/usr/local/bin/forwardx-agent"',
    'FXP_BIN="/usr/local/bin/forwardx-fxp"',
    'CONFIG_DIR="/etc/forwardx-agent"',
    'SERVICE_NAME="forwardx-agent"',
    '',
    '# 非交互兜底：如果未传 ACTION，但已携带 token（参数或嵌入），默认执行 install。',
    '# 这样可避免入口脚本/管道参数异常时落入交互菜单。',
    'if [ -z "$ACTION" ] && [ ! -t 0 ]; then',
    '  if [ -n "$TOKEN" ] || [ -n "$EMBEDDED_TOKEN" ]; then',
    '    ACTION="install"',
    '  fi',
    'fi',
    '',
    'show_help() {',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 管理工具"',
    '  echo "======================================"',
    '  echo ""',
    '  echo "用法:"',
    '  echo "  安装 Agent:"',
    '  echo "    curl -sL PANEL_URL/api/agent/install.sh | bash -s -- install YOUR_TOKEN"',
    '  echo ""',
    '  echo "  卸载 Agent:"',
    '  echo "    curl -sL PANEL_URL/api/agent/install.sh | bash -s -- uninstall"',
    '  echo ""',
    '  echo "  升级 Agent:"',
    '  echo "    curl -sL PANEL_URL/api/agent/install.sh | bash -s -- upgrade"',
    '  echo ""',
    '  echo "参数:"',
    '  echo "  install   <TOKEN>  安装 Agent 并注册到面板"',
    '  echo "  upgrade   [TOKEN]  升级 Agent，默认复用现有配置"',
    '  echo "  uninstall          完全卸载 Agent 及相关组件"',
    '  echo ""',
    '}',
    '',
    '# ============ 工具函数 ============',
    '',
    'resolve_token() {',
    '  if [ -n "$TOKEN" ]; then',
    '    AGENT_TOKEN="$TOKEN"',
    '  elif [ -n "$EMBEDDED_TOKEN" ]; then',
    '    AGENT_TOKEN="$EMBEDDED_TOKEN"',
    '  else',
    '    echo "[错误] 缺少 Agent Token"',
    '    echo "用法: curl -sL PANEL_URL/api/agent/install.sh | bash -s -- install YOUR_TOKEN"',
    '    exit 1',
    '  fi',
    '}',
    '',
    'detect_arch() {',
    '  case "$(uname -m)" in',
    '    x86_64|amd64) echo "amd64" ;;',
    '    aarch64|arm64) echo "arm64" ;;',
    '    *) echo "" ;;',
    '  esac',
    '}',
    '',
    'download_binary() {',
    '  local URL="$1" DST="$2" LABEL="$3"',
    '  echo "[信息] 下载 $LABEL: $URL"',
    '  if curl -fsSL --max-time 60 "$URL" -o "${DST}.tmp" 2>/dev/null && [ -s "${DST}.tmp" ]; then',
    '    install -m 0755 "${DST}.tmp" "$DST"',
    '    rm -f "${DST}.tmp"',
    '    echo "[信息] $LABEL 安装完成"',
    '    return 0',
    '  fi',
    '  rm -f "${DST}.tmp"',
    '  echo "[警告] $LABEL 下载失败"',
    '  return 1',
    '}',
    '',
    '# ============ 卸载 ============',
    '',
    'do_uninstall() {',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 卸载程序"',
    '  echo "======================================"',
    '  echo ""',
    '',
    '  if [ "$(id -u)" != "0" ]; then',
    '    echo "[错误] 请使用 root 权限运行此脚本"',
    '    exit 1',
    '  fi',
    '',
    '  echo "[步骤 1/5] 停止 Agent 服务..."',
    '  if systemctl is-active --quiet "$SERVICE_NAME" 2>/dev/null; then',
    '    systemctl stop "$SERVICE_NAME"',
    '    echo "[信息] 服务已停止"',
    '  else',
    '    echo "[信息] 服务未在运行"',
    '  fi',
    '',
    '  echo "[步骤 2/5] 禁用并删除 systemd 服务..."',
    '  if [ -f "/etc/systemd/system/$SERVICE_NAME.service" ]; then',
    '    systemctl disable "$SERVICE_NAME" 2>/dev/null || true',
    '    rm -f "/etc/systemd/system/$SERVICE_NAME.service"',
    '    systemctl daemon-reload',
    '    echo "[信息] 服务文件已删除"',
    '  fi',
    '',
    '  echo "[步骤 3/5] 清理 Go Agent 二进制和配置..."',
    '  rm -f "$GO_AGENT_BIN" "$FXP_BIN"',
    '  rm -rf "$CONFIG_DIR"',
    '  echo "[信息] Go Agent 文件已删除"',
    '',
    '  echo "[步骤 4/5] 清理转发进程和 iptables 规则..."',
    '  for pid in $(pgrep -f "[/]usr/local/bin/forwardx-fxp" 2>/dev/null || true); do if [ "$pid" = "$$" ] || [ "$pid" = "$PPID" ]; then continue; fi; kill "$pid" 2>/dev/null || true; done',
    '  for SVC in /etc/systemd/system/forwardx-socat-*.service /etc/systemd/system/forwardx-realm-*.service /etc/systemd/system/forwardx-gost-*.service; do',
    '    if [ -f "$SVC" ]; then',
    '      SVCNAME=$(basename "$SVC" .service)',
    '      systemctl stop "$SVCNAME" 2>/dev/null || true',
    '      systemctl disable "$SVCNAME" 2>/dev/null || true',
    '      rm -f "$SVC"',
    '      echo "[信息] 已删除服务: $SVCNAME"',
    '    fi',
    '  done',
    '  systemctl daemon-reload 2>/dev/null || true',
    '',
    '  # 清理 mangle 表中的 FWX 计数链',
    '  for CH in $(iptables -t mangle -L 2>/dev/null | awk \'/^Chain FWX_/ {print $2}\'); do',
    '    for P in tcp udp; do',
    '      iptables -t mangle -D PREROUTING -p $P -j "$CH" 2>/dev/null || true',
    '      iptables -t mangle -D POSTROUTING -p $P -j "$CH" 2>/dev/null || true',
    '      iptables -t mangle -D INPUT -p $P -j "$CH" 2>/dev/null || true',
    '      iptables -t mangle -D OUTPUT -p $P -j "$CH" 2>/dev/null || true',
    '      iptables -t mangle -D FORWARD -p $P -j "$CH" 2>/dev/null || true',
    '    done',
    '    iptables -t mangle -F "$CH" 2>/dev/null || true',
    '    iptables -t mangle -X "$CH" 2>/dev/null || true',
    '    echo "[信息] 已清理 mangle 计数链: $CH"',
    '  done',
    '',
    '  # 清理 filter 表中遗留的 FWX_LIMIT 链',
    '  for CH in $(iptables -L 2>/dev/null | awk \'/^Chain FWX_LIMIT_/ {print $2}\'); do',
    '    iptables -D INPUT -p tcp -j "$CH" 2>/dev/null || true',
    '    iptables -D FORWARD -p tcp -j "$CH" 2>/dev/null || true',
    '    iptables -F "$CH" 2>/dev/null || true',
    '    iptables -X "$CH" 2>/dev/null || true',
    '    echo "[信息] 已清理连接限制链: $CH"',
    '  done',
    '',
    '  # 清理 nat 表中的 DNAT/MASQUERADE 规则',
    '  while iptables -t nat -S PREROUTING 2>/dev/null | grep -q "DNAT"; do',
    '    RULE=$(iptables -t nat -S PREROUTING 2>/dev/null | grep "DNAT" | head -1 | sed "s/^-A/-D/")',
    '    [ -z "$RULE" ] && break',
    '    iptables -t nat $RULE 2>/dev/null || break',
    '  done',
    '  while iptables -t nat -S POSTROUTING 2>/dev/null | grep -q "MASQUERADE"; do',
    '    RULE=$(iptables -t nat -S POSTROUTING 2>/dev/null | grep "MASQUERADE" | head -1 | sed "s/^-A/-D/")',
    '    [ -z "$RULE" ] && break',
    '    iptables -t nat $RULE 2>/dev/null || break',
    '  done',
    '  echo "[信息] iptables 规则已清理"',
    '',
    '  echo "[步骤 5/5] 清理日志和状态文件..."',
    '  rm -rf /var/log/forwardx-agent 2>/dev/null || true',
    '  rm -rf /var/lib/forwardx-agent 2>/dev/null || true',
    '  echo "[信息] 日志和状态文件已删除"',
    '',
    '  echo ""',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 卸载完成!"',
    '  echo "======================================"',
    '  echo ""',
    '  echo "  如需重新安装，请使用 install 命令"',
    '  echo "======================================"',
    '}',
    '',
    '# ============ 安装依赖 ============',
    '',
    'install_deps() {',
    '  echo "[步骤 1/6] 安装系统依赖..."',
    '  if command -v apt-get >/dev/null 2>&1; then',
    '    export DEBIAN_FRONTEND=noninteractive',
    '    apt-get update -qq && apt-get install -y -qq curl jq socat iptables iproute2 coreutils systemd openssl iperf3 >/dev/null 2>&1 || true',
    '  elif command -v dnf >/dev/null 2>&1; then',
    '    dnf install -y -q curl jq socat iptables iproute coreutils systemd openssl iperf3 >/dev/null 2>&1 || true',
    '  elif command -v yum >/dev/null 2>&1; then',
    '    yum install -y -q curl jq socat iptables iproute coreutils systemd openssl iperf3 >/dev/null 2>&1 || true',
    '  elif command -v zypper >/dev/null 2>&1; then',
    '    zypper -n install curl jq socat iptables iproute2 coreutils systemd openssl iperf3 >/dev/null 2>&1 || true',
    '  elif command -v apk >/dev/null 2>&1; then',
    '    apk add --no-cache curl jq socat iptables iproute2 coreutils openrc openssl iperf3 >/dev/null 2>&1 || true',
    '  fi',
    '  # 验证关键依赖',
    '  for B in curl jq iptables iperf3; do',
    '    if ! command -v $B >/dev/null 2>&1; then',
    '      echo "[错误] 未能安装依赖: $B"',
    '      exit 1',
    '    fi',
    '  done',
    '  echo "[信息] 系统依赖就绪"',
    '}',
    '',
    'install_realm() {',
    '  if command -v realm >/dev/null 2>&1; then',
    '    echo "[信息] realm 已安装"',
    '    return 0',
    '  fi',
    '  echo "[信息] 安装 realm..."',
    '  REALM_VERSION="v2.6.0"',
    '  ARCH=$(uname -m)',
    '  case "$ARCH" in',
    '    x86_64|amd64) REALM_ARCH="x86_64-unknown-linux-gnu" ;;',
    '    aarch64|arm64) REALM_ARCH="aarch64-unknown-linux-gnu" ;;',
    '    *) echo "[警告] 不支持的架构: $ARCH, 跳过 realm"; return 1 ;;',
    '  esac',
    '  TMP=$(mktemp -d)',
    '  URL="https://github.com/zhboner/realm/releases/download/$REALM_VERSION/realm-$REALM_ARCH.tar.gz"',
    '  if curl -fsSL --max-time 60 "$URL" -o "$TMP/realm.tgz"; then',
    '    tar -xzf "$TMP/realm.tgz" -C "$TMP" 2>/dev/null || true',
    '    REALM_BIN=$(find "$TMP" -type f -name realm | head -n1)',
    '    if [ -n "$REALM_BIN" ]; then',
    '      install -m 0755 "$REALM_BIN" /usr/local/bin/realm',
    '      rm -rf "$TMP"',
    '      echo "[信息] realm 安装完成"',
    '      return 0',
    '    fi',
    '  fi',
    '  rm -rf "$TMP"',
    '  echo "[警告] realm 安装失败，realm 转发方式将不可用"',
    '  return 1',
    '}',
    '',
    'gost_self_check() {',
    '  local BIN="$1"',
    '  [ -n "$BIN" ] || BIN="$(command -v gost 2>/dev/null || true)"',
    '  [ -x "$BIN" ] || return 1',
    '  "$BIN" -V >/dev/null 2>&1 || "$BIN" --version >/dev/null 2>&1',
    '}',
    '',
    'install_gost() {',
    '  if gost_self_check "/usr/local/bin/gost"; then',
    '    echo "[info] gost already available"',
    '    return 0',
    '  fi',
    '  if command -v gost >/dev/null 2>&1 && ! gost_self_check "$(command -v gost)"; then',
    '    echo "[warn] installed gost is incompatible with current CPU, reinstalling"',
    '  fi',
    '  echo "[info] installing gost..."',
    '  GOST_VERSION="${GOST_VERSION:-3.2.6}"',
    '  GOST_VERSION="${GOST_VERSION#v}"',
    '  ARCH=$(uname -m)',
    '  case "$ARCH" in',
    '    x86_64|amd64) GOST_ARCHS="amd64v1 amd64 amd64v2 amd64v3" ;;',
    '    aarch64|arm64) GOST_ARCHS="arm64" ;;',
    '    *) echo "[warn] unsupported architecture: $ARCH, skip gost"; return 1 ;;',
    '  esac',
    '  TMP=$(mktemp -d)',
    '  for GOST_ARCH in $GOST_ARCHS; do',
    '    URL="https://github.com/go-gost/gost/releases/download/v${GOST_VERSION}/gost_${GOST_VERSION}_linux_${GOST_ARCH}.tar.gz"',
    '    if curl -fsSL --max-time 90 "$URL" -o "$TMP/gost.tgz"; then',
    '      tar -xzf "$TMP/gost.tgz" -C "$TMP" && \\',
    '        GOST_BIN=$(find "$TMP" -type f -name gost | head -n1) && \\',
    '        [ -n "$GOST_BIN" ] && install -m 0755 "$GOST_BIN" /usr/local/bin/gost && \\',
    '        gost_self_check "/usr/local/bin/gost" && \\',
    '        rm -rf "$TMP" && echo "[info] gost installed: $GOST_ARCH" && return 0',
    '    fi',
    '  done',
    '  rm -rf "$TMP"',
    '  echo "[warn] gost install failed, gost forward mode unavailable"',
    '  return 1',
    '}',
    '',
    'install_go_agent() {',
    '  GO_ARCH=$(detect_arch)',
    '  if [ -z "$GO_ARCH" ]; then',
    '    echo "[错误] 不支持的 CPU 架构: $(uname -m)"',
    '    return 1',
    '  fi',
    '',
    '  echo "[步骤 3/6] 安装 Go Agent v${RELEASE_VERSION}..."',
    '  AGENT_URL="https://github.com/poouo/Forwardx/releases/download/v${RELEASE_VERSION}/forwardx-agent-linux-${GO_ARCH}"',
    '  if ! download_binary "$AGENT_URL" "$GO_AGENT_BIN" "Go Agent"; then',
    '    echo "[错误] Go Agent 二进制下载失败，请检查网络或 Release 版本"',
    '    return 1',
    '  fi',
    '',
    '  echo "[步骤 4/6] 安装 ForwardX Tunnel Runtime..."',
    '  FXP_URL="https://github.com/poouo/Forwardx/releases/download/v${RELEASE_VERSION}/forwardx-fxp-linux-${GO_ARCH}"',
    '  download_binary "$FXP_URL" "$FXP_BIN" "ForwardX FXP" || \\',
    '    echo "[警告] FXP 安装失败，加密隧道功能将不可用（iptables/realm/socat/gost 转发不受影响）"',
    '',
    '  return 0',
    '}',
    '',
    '# ============ 安装 ============',
    '',
    'do_install() {',
    '  if [ "$(id -u)" != "0" ]; then',
    '    echo "[错误] 请使用 root 权限运行此脚本"',
    '    exit 1',
    '  fi',
    '',
    '  resolve_token',
    '',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 安装程序"',
    '  echo "======================================"',
    '  echo "面板地址: $PANEL_URL"',
    '  echo "Token: ${AGENT_TOKEN:0:8}***"',
    '  echo ""',
    '',
    '  # 安装系统依赖',
    '  install_deps',
    '',
    '  # 启用内核转发和 conntrack 计数器',
    '  echo "[步骤 2/6] 配置内核参数..."',
    '  sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1 || true',
    '  sysctl -w net.netfilter.nf_conntrack_acct=1 >/dev/null 2>&1 || true',
    '  if ! grep -qE "^\\s*net\\.ipv4\\.ip_forward\\s*=\\s*1" /etc/sysctl.conf 2>/dev/null; then',
    '    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf',
    '  fi',
    '  if ! grep -qE "^\\s*net\\.netfilter\\.nf_conntrack_acct\\s*=\\s*1" /etc/sysctl.conf 2>/dev/null; then',
    '    echo "net.netfilter.nf_conntrack_acct=1" >> /etc/sysctl.conf',
    '  fi',
    '  sysctl -p >/dev/null 2>&1 || true',
    '  echo "[信息] 内核参数就绪"',
    '',
    '  # 安装 Go Agent 二进制',
    '  if ! install_go_agent; then',
    '    echo "[错误] Go Agent 安装失败，安装中止"',
    '    exit 1',
    '  fi',
    '',
    '  # 安装可选转发工具',
    '  install_realm || true',
    '  install_gost || true',
    '',
    '  # 创建配置',
    '  echo "[步骤 5/6] 配置 Agent..."',
    '  mkdir -p "$CONFIG_DIR"',
    '  cat > "$CONFIG_DIR/config.json" << EOF',
    '{',
    '  "panelUrl": "$PANEL_URL",',
    '  "token": "$AGENT_TOKEN",',
    '  "interval": 30',
    '}',
    'EOF',
    '  echo "[信息] 配置文件已写入: $CONFIG_DIR/config.json"',
    '',
    '  # 安装 systemd 服务',
    '  cat > "/etc/systemd/system/$SERVICE_NAME.service" << EOF',
    '[Unit]',
    'Description=ForwardX Agent',
    'After=network.target',
    '',
    '[Service]',
    'Type=simple',
    'ExecStart=$GO_AGENT_BIN -config $CONFIG_DIR/config.json',
    'Restart=always',
    'RestartSec=10',
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    'EOF',
    '',
    '  systemctl daemon-reload',
    '  systemctl enable "$SERVICE_NAME"',
    '  systemctl restart "$SERVICE_NAME"',
    '  echo "[信息] systemd 服务已创建并启动"',
    '',
    '  # 注册到面板',
    '  echo "[步骤 6/6] 注册到面板..."',
    '  PUBLIC_IP=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || curl -s --max-time 5 icanhazip.com 2>/dev/null || echo "unknown")',
    '  OS_INFO=$(cat /etc/os-release 2>/dev/null | grep PRETTY_NAME | cut -d\'"\' -f2 || uname -s)',
    '  CPU_INFO=$(grep "model name" /proc/cpuinfo 2>/dev/null | head -1 | cut -d\':\' -f2 | xargs || echo "Unknown")',
    '  MEM_TOTAL=$(grep MemTotal /proc/meminfo 2>/dev/null | awk \'{print $2}\' || echo "0")',
    '',
    '  # 构建注册 payload 并加密',
    '  REGISTER_PAYLOAD=$(jq -n \\',
    '    --arg token "$AGENT_TOKEN" \\',
    '    --arg ip "$PUBLIC_IP" \\',
    '    --arg os "$OS_INFO" \\',
    '    --arg cpu "$CPU_INFO" \\',
    '    --arg agentVersion "$AGENT_VERSION" \\',
    '    --argjson mem "$((MEM_TOTAL * 1024))" \\',
    '    \'{token: $token, ip: $ip, osInfo: $os, cpuInfo: $cpu, memoryTotal: $mem, agentVersion: $agentVersion}\')',
    '',
    '  if command -v openssl >/dev/null 2>&1 && command -v xxd >/dev/null 2>&1; then',
    '    KEY_ENC_HEX=$(printf "%s|forwardx-agent-v1" "$AGENT_TOKEN" | openssl dgst -sha256 -hex 2>/dev/null | awk \'{print $NF}\')',
    '    KEY_MAC_HEX=$(printf "%s|forwardx-agent-mac" "$AGENT_TOKEN" | openssl dgst -sha256 -hex 2>/dev/null | awk \'{print $NF}\')',
    '    IV_HEX=$(openssl rand -hex 16)',
    '    CT_HEX=$(printf "%s" "$REGISTER_PAYLOAD" | openssl enc -aes-256-ctr -K "$KEY_ENC_HEX" -iv "$IV_HEX" 2>/dev/null | xxd -p -c 99999 | tr -d "\\n")',
    '    TS_MS=$(($(date +%s%N) / 1000000))',
    '    TS_HEX=$(printf "%016x" "$TS_MS")',
    '    MAC_HEX=$(printf "7631%s%s%s" "$IV_HEX" "$CT_HEX" "$TS_HEX" | xxd -r -p | openssl dgst -sha256 -mac HMAC -macopt hexkey:"$KEY_MAC_HEX" 2>/dev/null | awk \'{print $NF}\')',
    '    ENV_JSON=$(printf \'{"v":1,"iv":"%s","ct":"%s","mac":"%s","ts":%s}\' "$IV_HEX" "$CT_HEX" "$MAC_HEX" "$TS_MS")',
    '    curl -s --max-time 10 -X POST "$PANEL_URL/api/agent/register" \\',
    '      -H "Content-Type: application/json" \\',
    '      -H "Authorization: Bearer $AGENT_TOKEN" \\',
    '      -H "X-Agent-Encrypted: 1" \\',
    '      -d "$ENV_JSON"',
    '  else',
    '    echo "[警告] openssl/xxd 不可用，以明文注册（不推荐）"',
    '    curl -s --max-time 10 -X POST "$PANEL_URL/api/agent/register" \\',
    '      -H "Content-Type: application/json" \\',
    '      -H "Authorization: Bearer $AGENT_TOKEN" \\',
    '      -d "$REGISTER_PAYLOAD"',
    '  fi',
    '',
    '  echo ""',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 安装完成!"',
    '  echo "======================================"',
    '  echo "  Go Agent:  $GO_AGENT_BIN"',
    '  echo "  配置文件:  $CONFIG_DIR/config.json"',
    '  echo "  服务名称:  $SERVICE_NAME"',
    '  echo "  查看状态:  systemctl status $SERVICE_NAME"',
    '  echo "  查看日志:  journalctl -u $SERVICE_NAME -f"',
    '  echo "  卸载命令:  curl -sL $PANEL_URL/api/agent/install.sh | bash -s -- uninstall"',
    '  echo "======================================"',
    '}',
    '',
    '# ============ 升级 ============',
    '',
    'do_upgrade() {',
    '  if [ "$(id -u)" != "0" ]; then',
    '    echo "[错误] 请使用 root 权限运行此脚本"',
    '    exit 1',
    '  fi',
    '',
    '  # 尝试从现有配置文件读取',
    '  if [ -f "$CONFIG_DIR/config.json" ]; then',
    '    EXISTING_PANEL_URL=$(jq -r ".panelUrl // empty" "$CONFIG_DIR/config.json" 2>/dev/null || true)',
    '    EXISTING_TOKEN=$(jq -r ".token // empty" "$CONFIG_DIR/config.json" 2>/dev/null || true)',
    '  fi',
    '',
    '  PANEL_URL="${PANEL_URL:-${EXISTING_PANEL_URL:-}}"',
    '  if [ -n "$TOKEN" ]; then',
    '    AGENT_TOKEN="$TOKEN"',
    '  elif [ -n "$EMBEDDED_TOKEN" ]; then',
    '    AGENT_TOKEN="$EMBEDDED_TOKEN"',
    '  else',
    '    AGENT_TOKEN="${EXISTING_TOKEN:-}"',
    '  fi',
    '',
    '  if [ -z "$PANEL_URL" ]; then',
    '    echo "[错误] 未找到面板地址"',
    '    exit 1',
    '  fi',
    '',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 升级程序"',
    '  echo "======================================"',
    '  echo "面板地址: $PANEL_URL"',
    '  echo ""',
    '',
    '  # 下载并替换 Go Agent 二进制',
    '  GO_ARCH=$(detect_arch)',
    '  if [ -z "$GO_ARCH" ]; then',
    '    echo "[错误] 不支持的 CPU 架构"',
    '    exit 1',
    '  fi',
    '',
    '  echo "[信息] 升级 Go Agent v${RELEASE_VERSION}..."',
    '  AGENT_URL="https://github.com/poouo/Forwardx/releases/download/v${RELEASE_VERSION}/forwardx-agent-linux-${GO_ARCH}"',
    '  if download_binary "$AGENT_URL" "$GO_AGENT_BIN" "Go Agent"; then',
    '    FXP_URL="https://github.com/poouo/Forwardx/releases/download/v${RELEASE_VERSION}/forwardx-fxp-linux-${GO_ARCH}"',
    '    download_binary "$FXP_URL" "$FXP_BIN" "ForwardX FXP" || true',
    '    install_deps',
    '    install_gost || true',
    '',
    '    # 更新配置中的 token（如有提供）',
    '    if [ -n "$AGENT_TOKEN" ] && [ -f "$CONFIG_DIR/config.json" ]; then',
    '      jq --arg t "$AGENT_TOKEN" \'.token = $t\' "$CONFIG_DIR/config.json" > "$CONFIG_DIR/config.json.tmp" && \\',
    '        mv "$CONFIG_DIR/config.json.tmp" "$CONFIG_DIR/config.json"',
    '    fi',
    '',
    '    # 重启服务',
    '    systemctl restart "$SERVICE_NAME"',
    '    echo ""',
    '    echo "======================================"',
    '    echo "  ForwardX Agent 升级完成!"',
    '    echo "======================================"',
    '  else',
    '    echo "[错误] 升级失败"',
    '    exit 1',
    '  fi',
    '}',
    '',
    '# ============ 入口 ============',
    '',
    'case "$ACTION" in',
    '  install)',
    '    do_install',
    '    ;;',
    '  upgrade|update)',
    '    do_upgrade',
    '    ;;',
    '  uninstall|remove|delete)',
    '    do_uninstall',
    '    ;;',
    '  *)',
    '    show_help',
    '    if [ -n "$ACTION" ]; then',
    '      echo "[提示] 未知操作: $ACTION"',
    '      echo ""',
    '    fi',
    '    echo "请选择操作:"',
    '    echo "  1) 安装 Agent"',
    '    echo "  2) 卸载 Agent"',
    '    echo "  3) 升级 Agent"',
    '    echo ""',
    '    read -p "请输入选项 [1/2/3]: " CHOICE',
    '    case "$CHOICE" in',
    '      1)',
    '        read -p "请输入 Agent Token: " INPUT_TOKEN',
    '        read -p "请输入面板地址 [$PANEL_URL]: " INPUT_URL',
    '        if [ -n "$INPUT_URL" ]; then',
    '          PANEL_URL="$INPUT_URL"',
    '        fi',
    '        TOKEN="$INPUT_TOKEN"',
    '        do_install',
    '        ;;',
    '      2)',
    '        do_uninstall',
    '        ;;',
    '      3)',
    '        read -p "请输入面板地址（留空则读取现有安装）[$PANEL_URL]: " INPUT_URL',
    '        if [ -n "$INPUT_URL" ]; then',
    '          PANEL_URL="$INPUT_URL"',
    '        fi',
    '        do_upgrade',
    '        ;;',
    '      *)',
    '        echo "[错误] 无效选项"',
    '        exit 1',
    '        ;;',
    '    esac',
    '    ;;',
    'esac',
    'exit 0',
  ];
  return lines.join('\n') + '\n';
}
