import { APP_VERSION } from "./_core/systemRouter";

function getPreviousReleaseVersion(version: string) {
  const normalized = String(version || "").trim().replace(/^v/i, "");
  const match = normalized.match(/^(\d+)\.(\d+)\.(\d+)$/);
  if (!match) return "";
  const patch = Number(match[3]);
  if (!Number.isSafeInteger(patch) || patch <= 0) return "";
  return `${match[1]}.${match[2]}.${patch - 1}`;
}

type AgentInstallScriptOptions = {
  githubAcceleratorEnabled?: boolean;
  githubAcceleratorUrl?: string | null;
  preferPanelInstall?: boolean;
};

function shellQuote(value: string) {
  return `'${String(value).replace(/'/g, "'\\''")}'`;
}

/**
 * 生成 Go Agent 一键安装脚本（自包含，不依赖 Shell Agent）。
 *
 * 用法：
 *   curl -sL PANEL_URL/api/agent/install.sh | bash -s -- install YOUR_TOKEN
 *   curl -sL PANEL_URL/api/agent/install.sh | bash -s -- upgrade
 *   curl -sL PANEL_URL/api/agent/install.sh | bash -s -- uninstall
 *
 * @param defaultPanelUrl 面板地址（当用户未通过 PANEL_URL 环境变量指定时使用）
 */
export function generateInstallScript(defaultPanelUrl: string, options: AgentInstallScriptOptions = {}): string {
  const fallbackReleaseVersion = getPreviousReleaseVersion(APP_VERSION);
  const fallbackReleaseLine = fallbackReleaseVersion
    ? `FALLBACK_RELEASE_VERSION="\${FALLBACK_RELEASE_VERSION:-${fallbackReleaseVersion}}"`
    : 'FALLBACK_RELEASE_VERSION="${FALLBACK_RELEASE_VERSION:-}"';
  const defaultGithubAcceleratorUrl = String(options.githubAcceleratorUrl || "").trim().replace(/\/+$/, "");
  const defaultGithubAcceleratorEnabled = !!options.githubAcceleratorEnabled && !!defaultGithubAcceleratorUrl;
  const defaultPreferPanelInstall = !!options.preferPanelInstall;
  const lines = [
    '#!/bin/bash',
    '# ForwardX Agent (Go) 一键安装/管理脚本',
    '# 安装: curl -sL PANEL_URL/api/agent/install.sh | bash -s -- install YOUR_TOKEN',
    '# 升级: curl -sL PANEL_URL/api/agent/install.sh | bash -s -- upgrade',
    '# 卸载: curl -sL PANEL_URL/api/agent/install.sh | bash -s -- uninstall',
    '',
    'set -e',
    '',
    'ACTION="${1:-}"',
    'TOKEN="${2:-}"',
    // 优先使用环境变量 PANEL_URL，其次使用脚本嵌入的默认值
    `PANEL_URL="\${PANEL_URL:-${defaultPanelUrl}}"`,
    `RELEASE_VERSION="\${FORWARDX_AGENT_RELEASE_VERSION:-${APP_VERSION}}"`,
    fallbackReleaseLine,
    `GITHUB_ACCELERATOR_DEFAULT_ENABLED="${defaultGithubAcceleratorEnabled ? "true" : "false"}"`,
    `GITHUB_ACCELERATOR_DEFAULT_URL=${shellQuote(defaultGithubAcceleratorUrl)}`,
    `FORWARDX_AGENT_PANEL_FIRST_DEFAULT="${defaultPreferPanelInstall ? "true" : "false"}"`,
    'GITHUB_ACCELERATOR_ENABLED="${GITHUB_ACCELERATOR_ENABLED:-$GITHUB_ACCELERATOR_DEFAULT_ENABLED}"',
    'GITHUB_ACCELERATOR_URL="${GITHUB_ACCELERATOR_URL:-$GITHUB_ACCELERATOR_DEFAULT_URL}"',
    'FORWARDX_AGENT_PANEL_FIRST="${FORWARDX_AGENT_PANEL_FIRST:-$FORWARDX_AGENT_PANEL_FIRST_DEFAULT}"',
    "FORWARDX_CURL_CONNECT_TIMEOUT=\"${FORWARDX_CURL_CONNECT_TIMEOUT:-15}\"",
    "FORWARDX_CURL_LOW_SPEED_LIMIT=\"${FORWARDX_CURL_LOW_SPEED_LIMIT:-1024}\"",
    "FORWARDX_CURL_ASSET_LOW_SPEED_TIME=\"${FORWARDX_CURL_ASSET_LOW_SPEED_TIME:-180}\"",
    'while [ "${GITHUB_ACCELERATOR_URL%/}" != "$GITHUB_ACCELERATOR_URL" ]; do',
    '  GITHUB_ACCELERATOR_URL="${GITHUB_ACCELERATOR_URL%/}"',
    'done',
    '',
    'GO_AGENT_BIN="/usr/local/bin/forwardx-agent"',
    'FXP_BIN="/usr/local/bin/forwardx-fxp"',
    'RUNTIME_BIN="/usr/local/bin/forwardx-runtime"',
    'CONFIG_DIR="/etc/forwardx-agent"',
    'SERVICE_NAME="forwardx-agent"',
    '',
    'shell_quote() {',
    '  printf "\\047%s\\047" "$(printf "%s" "$1" | sed "s/\\047/\\047\\\\\\\\\\047\\047/g")"',
    '}',
    '',
    'is_systemd_host() {',
    '  command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]',
    '}',
    '',
    'current_service_manager() {',
    '  if is_systemd_host; then',
    '    echo "systemd"',
    '  elif [ -x "/etc/init.d/$SERVICE_NAME" ] && head -n 1 "/etc/init.d/$SERVICE_NAME" 2>/dev/null | grep -q "openrc-run"; then',
    '    echo "openrc"',
    '  elif [ -x "/etc/init.d/$SERVICE_NAME" ]; then',
    '    echo "sysv"',
    '  elif command -v rc-service >/dev/null 2>&1 && command -v rc-update >/dev/null 2>&1; then',
    '    echo "openrc"',
    '  else',
    '    echo "unknown"',
    '  fi',
    '}',
    '',
    'print_agent_service_hints() {',
    '  case "$(current_service_manager)" in',
    '    systemd)',
    '      echo "  查看状态:  systemctl status $SERVICE_NAME"',
    '      echo "  查看日志:  journalctl -u $SERVICE_NAME -f"',
    '      ;;',
    '    openrc)',
    '      echo "  查看状态:  rc-service $SERVICE_NAME status"',
    '      echo "  查看日志:  tail -f /var/log/forwardx-agent/$SERVICE_NAME.log"',
    '      ;;',
    '    sysv)',
    '      echo "  查看状态:  /etc/init.d/$SERVICE_NAME status"',
    '      echo "  查看日志:  tail -f /var/log/forwardx-agent/agent-go.log"',
    '      ;;',
    '    *)',
    '      echo "  查看状态:  请使用当前系统的服务管理器查看 $SERVICE_NAME"',
    '      echo "  查看日志:  tail -f /var/log/forwardx-agent/agent-go.log"',
    '      ;;',
    '  esac',
    '}',
    '',
    'write_agent_openrc_service() {',
    '  cat > "/etc/init.d/$SERVICE_NAME" << EOF',
    '#!/sbin/openrc-run',
    'name="$SERVICE_NAME"',
    'description="ForwardX Agent"',
    'command="/bin/sh"',
    'command_args="-lc $(shell_quote "exec $GO_AGENT_BIN -config $CONFIG_DIR/config.json")"',
    'command_background=true',
    'pidfile="/run/$SERVICE_NAME.pid"',
    'output_log="/var/log/forwardx-agent/$SERVICE_NAME.log"',
    'error_log="/var/log/forwardx-agent/$SERVICE_NAME.log"',
    'depend() {',
    '  need net',
    '}',
    'EOF',
    '  chmod 755 "/etc/init.d/$SERVICE_NAME"',
    '}',
    '',
    'write_agent_sysv_service() {',
    '  cat > "/etc/init.d/$SERVICE_NAME" << EOF',
    '#!/bin/sh',
    '### BEGIN INIT INFO',
    '# Provides:          $SERVICE_NAME',
    '# Required-Start:    $network',
    '# Required-Stop:     $network',
    '# Default-Start:     2 3 4 5',
    '# Default-Stop:      0 1 6',
    '# Short-Description: ForwardX Agent',
    '### END INIT INFO',
    'PIDFILE=/run/$SERVICE_NAME.pid',
    'LOGFILE=/var/log/forwardx-agent/agent-go.log',
    'CMD=$(shell_quote "exec $GO_AGENT_BIN -config $CONFIG_DIR/config.json")',
    'start() {',
    '  mkdir -p /run /var/log/forwardx-agent',
    '  if [ -s "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then return 0; fi',
    '  nohup sh -lc "$CMD" >> "$LOGFILE" 2>&1 &',
    '  echo $! > "$PIDFILE"',
    '}',
    'stop() {',
    '  if [ -s "$PIDFILE" ]; then kill "$(cat "$PIDFILE")" 2>/dev/null || true; rm -f "$PIDFILE"; fi',
    '}',
    'case "$1" in',
    '  start) start ;;',
    '  stop) stop ;;',
    '  restart) stop; sleep 1; start ;;',
    '  status) [ -s "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null ;;',
    '  *) echo "Usage: $0 {start|stop|restart|status}"; exit 1 ;;',
    'esac',
    'EOF',
    '  chmod 755 "/etc/init.d/$SERVICE_NAME"',
    '}',
    '',
    'write_agent_service() {',
    '  mkdir -p /var/log/forwardx-agent',
    '  if is_systemd_host; then',
    '    cat > "/etc/systemd/system/$SERVICE_NAME.service" << EOF',
    '[Unit]',
    'Description=ForwardX Agent',
    'Wants=network-online.target time-sync.target',
    'After=network-online.target time-sync.target',
    '',
    '[Service]',
    'Type=simple',
    'ExecStart=$GO_AGENT_BIN -config $CONFIG_DIR/config.json',
    'Restart=always',
    'RestartSec=10',
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    'EOF',
    '    systemctl daemon-reload',
    '    systemctl enable "$SERVICE_NAME"',
    '    echo "[信息] systemd 服务已创建"',
    '  elif command -v rc-service >/dev/null 2>&1 && command -v rc-update >/dev/null 2>&1; then',
    '    write_agent_openrc_service',
    '    rc-update add "$SERVICE_NAME" default >/dev/null 2>&1 || true',
    '    echo "[信息] OpenRC 服务已创建"',
    '  elif [ -d /etc/init.d ]; then',
    '    write_agent_sysv_service',
    '    command -v update-rc.d >/dev/null 2>&1 && update-rc.d "$SERVICE_NAME" defaults >/dev/null 2>&1 || true',
    '    command -v chkconfig >/dev/null 2>&1 && chkconfig "$SERVICE_NAME" on >/dev/null 2>&1 || true',
    '    echo "[信息] SysV 服务已创建"',
    '  else',
    '    echo "[错误] 不支持的 init 系统，请安装 systemd、OpenRC 或 SysV init"',
    '    return 1',
    '  fi',
    '}',
    '',
    'start_agent_service() {',
    '  if is_systemd_host; then',
    '    if ! systemctl restart "$SERVICE_NAME"; then',
    '      echo "[错误] systemd 服务启动失败"',
    '      systemctl status "$SERVICE_NAME" --no-pager -l 2>/dev/null || true',
    '      return 1',
    '    fi',
    '    sleep 1',
    '    if ! systemctl is-active --quiet "$SERVICE_NAME"; then',
    '      echo "[错误] systemd 服务未保持运行"',
    '      systemctl status "$SERVICE_NAME" --no-pager -l 2>/dev/null || true',
    '      journalctl -u "$SERVICE_NAME" -n 50 --no-pager 2>/dev/null || true',
    '      return 1',
    '    fi',
    '  elif command -v rc-service >/dev/null 2>&1; then',
    '    rc-service "$SERVICE_NAME" restart || return 1',
    '  elif [ -x "/etc/init.d/$SERVICE_NAME" ]; then',
    '    "/etc/init.d/$SERVICE_NAME" restart || return 1',
    '  else',
    '    echo "[错误] 未找到可用的服务管理器"',
    '    return 1',
    '  fi',
    '  echo "[信息] Agent 服务已启动"',
    '}',
    '',
    'remove_service_by_name() {',
    '  local NAME="$1"',
    '  if is_systemd_host; then',
    '    systemctl stop "$NAME" 2>/dev/null || true',
    '    systemctl disable "$NAME" 2>/dev/null || true',
    '    rm -f "/etc/systemd/system/$NAME.service"',
    '    systemctl daemon-reload 2>/dev/null || true',
    '  fi',
    '  if command -v rc-service >/dev/null 2>&1; then rc-service "$NAME" stop 2>/dev/null || true; fi',
    '  if command -v rc-update >/dev/null 2>&1; then rc-update del "$NAME" default 2>/dev/null || true; fi',
    '  if [ -x "/etc/init.d/$NAME" ]; then "/etc/init.d/$NAME" stop 2>/dev/null || true; fi',
    '  command -v update-rc.d >/dev/null 2>&1 && update-rc.d -f "$NAME" remove >/dev/null 2>&1 || true',
    '  command -v chkconfig >/dev/null 2>&1 && chkconfig "$NAME" off >/dev/null 2>&1 || true',
    '  rm -f "/etc/init.d/$NAME"',
    '}',
    '',
    'show_help() {',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 管理工具"',
    '  echo "======================================"',
    '  echo ""',
    '  echo "用法:"',
    '  echo "  安装 Agent:"',
    '  echo "    curl -sL PANEL_URL/api/agent/install.sh | bash -s -- install YOUR_TOKEN"',
    '  echo ""',
    '  echo "  卸载 Agent:"',
    '  echo "    curl -sL PANEL_URL/api/agent/install.sh | bash -s -- uninstall"',
    '  echo ""',
    '  echo "  升级 Agent:"',
    '  echo "    curl -sL PANEL_URL/api/agent/install.sh | bash -s -- upgrade"',
    '  echo ""',
    '  echo "参数:"',
    '  echo "  install   <TOKEN>  安装 Agent 并注册到面板"',
    '  echo "  upgrade   [TOKEN]  升级 Agent，默认复用现有配置"',
    '  echo "  uninstall          完全卸载 Agent 及相关组件"',
    '  echo ""',
    '}',
    '',
    '# ============ 工具函数 ============',
    '',
    'resolve_token() {',
    '  if [ -n "$TOKEN" ]; then',
    '    AGENT_TOKEN="$TOKEN"',
    '  else',
    '    echo "[错误] 缺少 Agent Token"',
    '    echo "用法: curl -sL PANEL_URL/api/agent/install.sh | bash -s -- install YOUR_TOKEN"',
    '    exit 1',
    '  fi',
    '}',
    '',
    'detect_arch() {',
    '  case "$(uname -m)" in',
    '    x86_64|amd64) echo "amd64" ;;',
    '    aarch64|arm64) echo "arm64" ;;',
    '    *) echo "" ;;',
    '  esac',
    '}',
    '',
    'is_enabled_value() {',
    '  case "${1:-}" in',
    '    1|true|TRUE|yes|YES|on|ON) return 0 ;;',
    '    *) return 1 ;;',
    '  esac',
    '}',
    '',
    'is_github_accelerator_enabled() {',
    '  is_enabled_value "${GITHUB_ACCELERATOR_ENABLED:-}" && [ -n "${GITHUB_ACCELERATOR_URL:-}" ]',
    '}',
    '',
    'github_url() {',
    '  local URL="$1"',
    '  if is_github_accelerator_enabled; then',
    '    case "$URL" in',
    '      http://github.com/*|https://github.com/*|http://raw.githubusercontent.com/*|https://raw.githubusercontent.com/*)',
    '        printf "%s/%s\\n" "$GITHUB_ACCELERATOR_URL" "$URL"',
    '        return 0',
    '        ;;',
    '    esac',
    '  fi',
    '  printf "%s\\n" "$URL"',
    '}',
    '',
    'panel_asset_url() {',
    '  local VERSION="$1" ASSET="$2"',
    '  printf "%s/api/agent/assets/v%s/%s\\n" "${PANEL_URL%/}" "$VERSION" "$ASSET"',
    '}',
    '',
    'download_url_binary() {',
    "  local URL=\"$1\" DST=\"$2\" LABEL=\"$3\" LOW_SPEED_TIME=\"${4:-$FORWARDX_CURL_ASSET_LOW_SPEED_TIME}\" RC=0",
    '  DOWNLOAD_HTTP_STATUS="000"',
    '  rm -f "${DST}.tmp" "${DST}.status"',
    '  echo "[信息] 正在下载 $LABEL: $URL"',
    "  curl -fsSL --connect-timeout \"$FORWARDX_CURL_CONNECT_TIMEOUT\" --speed-limit \"$FORWARDX_CURL_LOW_SPEED_LIMIT\" --speed-time \"$LOW_SPEED_TIME\" -w \"%{http_code}\" \"$URL\" -o \"${DST}.tmp\" > \"${DST}.status\" 2>/dev/null || RC=$?",
    '  if [ -s "${DST}.status" ]; then',
    '    DOWNLOAD_HTTP_STATUS="$(cat "${DST}.status" 2>/dev/null || printf "000")"',
    '  fi',
    '  if [ "$RC" = "0" ] && [ -s "${DST}.tmp" ]; then',
    '    install -m 0755 "${DST}.tmp" "$DST"',
    '    rm -f "${DST}.tmp" "${DST}.status"',
    '    echo "[信息] $LABEL 安装完成"',
    '    return 0',
    '  fi',
    '  rm -f "${DST}.tmp" "${DST}.status"',
    '  if [ "$DOWNLOAD_HTTP_STATUS" = "404" ]; then',
    '    echo "[信息] 未找到 $LABEL 资产，继续尝试其他来源: $URL"',
    '    return 2',
    '  fi',
    '  echo "[警告] $LABEL 下载失败（HTTP=${DOWNLOAD_HTTP_STATUS}, 退出码=${RC}）"',
    '  return 1',
    '}',
    '',
    'download_github_binary() {',
    '  local URL="$1" DST="$2" LABEL="$3"',
    '  local RAW_URL="$URL" RC=0 DIRECT_RC=0',
    '  URL="$(github_url "$URL")"',
    '  if download_url_binary "$URL" "$DST" "$LABEL"; then',
    '    return 0',
    '  else',
    '    RC=$?',
    '  fi',
    '  if [ "$RC" = "2" ] && [ "$URL" != "$RAW_URL" ]; then',
    '    echo "[信息] 加速源未找到 $LABEL，正在验证 GitHub 原始地址..."',
    '    if download_url_binary "$RAW_URL" "$DST" "$LABEL"; then',
    '      return 0',
    '    else',
    '      DIRECT_RC=$?',
    '    fi',
    '    if [ "$DIRECT_RC" = "2" ]; then',
    '      return 2',
    '    fi',
    '    return 1',
    '  fi',
    '  return "$RC"',
    '}',
    '',
    'download_panel_binary() {',
    '  local URL="$1" DST="$2" LABEL="$3"',
    "  download_url_binary \"$URL\" \"$DST\" \"$LABEL\" \"$FORWARDX_CURL_ASSET_LOW_SPEED_TIME\"",
    '}',
    '',
    'download_current_release_binary() {',
    '  local ASSET="$1" DST="$2" LABEL="$3"',
    '  local URL PANEL_TRIED=0 GITHUB_RC=1 PANEL_RC=1',
    '  if is_enabled_value "${FORWARDX_AGENT_PANEL_FIRST:-}"; then',
    '    PANEL_TRIED=1',
    '    URL="$(panel_asset_url "$RELEASE_VERSION" "$ASSET")"',
    '    if download_panel_binary "$URL" "$DST" "$LABEL"; then',
    '      DOWNLOADED_RELEASE_VERSION="$RELEASE_VERSION"',
    '      return 0',
    '    else',
    '      PANEL_RC=$?',
    '    fi',
    '    echo "[信息] 面板端暂未提供 $LABEL，尝试从 GitHub 下载..."',
    '  fi',
    '  URL="https://github.com/poouo/Forwardx/releases/download/v${RELEASE_VERSION}/${ASSET}"',
    '  if download_github_binary "$URL" "$DST" "$LABEL"; then',
    '    DOWNLOADED_RELEASE_VERSION="$RELEASE_VERSION"',
    '    return 0',
    '  else',
    '    GITHUB_RC=$?',
    '  fi',
    '  if [ "$PANEL_TRIED" != "1" ]; then',
    '    URL="$(panel_asset_url "$RELEASE_VERSION" "$ASSET")"',
    '    if download_panel_binary "$URL" "$DST" "$LABEL"; then',
    '      DOWNLOADED_RELEASE_VERSION="$RELEASE_VERSION"',
    '      return 0',
    '    else',
    '      PANEL_RC=$?',
    '    fi',
    '  fi',
    '  if [ "$GITHUB_RC" = "2" ]; then',
    '    return 2',
    '  fi',
    '  return 1',
    '}',
    '',
    'download_release_binary() {',
    '  local ASSET="$1" DST="$2" LABEL="$3" ALLOW_FALLBACK="${4:-0}"',
    '  local CURRENT_RC=1 URL',
    '  DOWNLOADED_RELEASE_VERSION=""',
    '  if download_current_release_binary "$ASSET" "$DST" "$LABEL"; then',
    '    return 0',
    '  else',
    '    CURRENT_RC=$?',
    '  fi',
    '  if [ "$CURRENT_RC" = "2" ] && [ "$ALLOW_FALLBACK" = "1" ] && [ -n "$FALLBACK_RELEASE_VERSION" ] && [ "$FALLBACK_RELEASE_VERSION" != "$RELEASE_VERSION" ]; then',
    '    echo "[信息] v${RELEASE_VERSION} 的 $LABEL 资产暂未就绪，尝试回退到上一版本 v${FALLBACK_RELEASE_VERSION}..."',
    '    if is_enabled_value "${FORWARDX_AGENT_PANEL_FIRST:-}"; then',
    '      URL="$(panel_asset_url "$FALLBACK_RELEASE_VERSION" "$ASSET")"',
    '      if download_panel_binary "$URL" "$DST" "$LABEL"; then',
    '        DOWNLOADED_RELEASE_VERSION="$FALLBACK_RELEASE_VERSION"',
    '        echo "[信息] 临时使用上一版本 v${FALLBACK_RELEASE_VERSION} 的 $LABEL"',
    '        return 0',
    '      fi',
    '      echo "[信息] 面板端上一版本 $LABEL 不可用，尝试从 GitHub 下载..."',
    '    fi',
    '    URL="https://github.com/poouo/Forwardx/releases/download/v${FALLBACK_RELEASE_VERSION}/${ASSET}"',
    '    if download_github_binary "$URL" "$DST" "$LABEL"; then',
    '      DOWNLOADED_RELEASE_VERSION="$FALLBACK_RELEASE_VERSION"',
    '      echo "[信息] 临时使用上一版本 v${FALLBACK_RELEASE_VERSION} 的 $LABEL"',
    '      return 0',
    '    fi',
    '    if ! is_enabled_value "${FORWARDX_AGENT_PANEL_FIRST:-}"; then',
    '      URL="$(panel_asset_url "$FALLBACK_RELEASE_VERSION" "$ASSET")"',
    '      if download_panel_binary "$URL" "$DST" "$LABEL"; then',
    '        DOWNLOADED_RELEASE_VERSION="$FALLBACK_RELEASE_VERSION"',
    '        echo "[信息] 临时使用上一版本 v${FALLBACK_RELEASE_VERSION} 的 $LABEL"',
    '        return 0',
    '      fi',
    '    fi',
    '  elif [ "$CURRENT_RC" != "2" ]; then',
    '    echo "[信息] 当前 $LABEL 因网络或服务异常下载失败，跳过上一版本回退"',
    '  fi',
    '  return 1',
    '}',
    '',
    '# ============ 卸载 ============',
    '',
    'do_uninstall() {',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 卸载程序"',
    '  echo "======================================"',
    '  echo ""',
    '',
    '  if [ "$(id -u)" != "0" ]; then',
    '    echo "[错误] 请使用 root 权限运行此脚本"',
    '    exit 1',
    '  fi',
    '',
    '  echo "[步骤 1/5] 停止 Agent 服务..."',
    '  if remove_service_by_name "$SERVICE_NAME"; then',
    '    :',
    '    echo "[信息] 服务已停止"',
    '  else',
    '    echo "[信息] 服务未在运行"',
    '  fi',
    '',
    '  echo "[步骤 2/5] 禁用并删除 systemd 服务..."',
    '  if false && [ -f "/etc/systemd/system/$SERVICE_NAME.service" ]; then',
    '    systemctl disable "$SERVICE_NAME" 2>/dev/null || true',
    '    rm -f "/etc/systemd/system/$SERVICE_NAME.service"',
    '    systemctl daemon-reload',
    '    echo "[信息] 服务文件已删除"',
    '  fi',
    '',
    '  echo "[步骤 3/5] 清理 Go Agent 二进制和配置..."',
    '  rm -f "$GO_AGENT_BIN" "$FXP_BIN" "$RUNTIME_BIN"',
    '  rm -rf "$CONFIG_DIR"',
    '  echo "[信息] Go Agent 文件已删除"',
    '',
    '  echo "[步骤 4/5] 清理转发进程和 iptables 规则..."',
    '  for pid in $(pgrep -f "[/]usr/local/bin/forwardx-fxp" 2>/dev/null || true); do if [ "$pid" = "$$" ] || [ "$pid" = "$PPID" ]; then continue; fi; kill "$pid" 2>/dev/null || true; done',
    '  for pid in $(pgrep -f "[/]usr/local/bin/forwardx-runtime" 2>/dev/null || true); do if [ "$pid" = "$$" ] || [ "$pid" = "$PPID" ]; then continue; fi; kill "$pid" 2>/dev/null || true; done',
    '  for SVC in /etc/systemd/system/forwardx-socat-*.service /etc/systemd/system/forwardx-realm-*.service /etc/systemd/system/forwardx-gost-*.service /etc/systemd/system/forwardx-runtime.service /etc/systemd/system/forwardx-tunnel-runtime.service /etc/systemd/system/forwardx-gost.service /etc/systemd/system/forwardx-tunnels.service; do',
    '    if [ -f "$SVC" ]; then',
    '      SVCNAME=$(basename "$SVC" .service)',
    '      remove_service_by_name "$SVCNAME"',
    '      echo "[信息] 已删除服务: $SVCNAME"',
    '    fi',
    '  done',
    '  for SVC in /etc/init.d/forwardx-socat-* /etc/init.d/forwardx-realm-* /etc/init.d/forwardx-gost-* /etc/init.d/forwardx-runtime /etc/init.d/forwardx-tunnel-runtime /etc/init.d/forwardx-gost /etc/init.d/forwardx-tunnels; do',
    '    if [ -f "$SVC" ]; then',
    '      SVCNAME=$(basename "$SVC")',
    '      remove_service_by_name "$SVCNAME"',
    '      echo "[淇℃伅] 宸插垹闄ゆ湇鍔? $SVCNAME"',
    '    fi',
    '  done',
    '',
    '  # 清理 mangle 表中的 FWX 计数链',
    '  for CH in $(iptables -t mangle -L 2>/dev/null | awk \'/^Chain FWX_/ {print $2}\'); do',
    '    for P in tcp udp; do',
    '      iptables -t mangle -D PREROUTING -p $P -j "$CH" 2>/dev/null || true',
    '      iptables -t mangle -D POSTROUTING -p $P -j "$CH" 2>/dev/null || true',
    '      iptables -t mangle -D INPUT -p $P -j "$CH" 2>/dev/null || true',
    '      iptables -t mangle -D OUTPUT -p $P -j "$CH" 2>/dev/null || true',
    '      iptables -t mangle -D FORWARD -p $P -j "$CH" 2>/dev/null || true',
    '    done',
    '    iptables -t mangle -F "$CH" 2>/dev/null || true',
    '    iptables -t mangle -X "$CH" 2>/dev/null || true',
    '    echo "[信息] 已清理 mangle 计数链: $CH"',
    '  done',
    '',
    '  # 清理 filter 表中遗留的 FWX_LIMIT 链',
    '  for CH in $(iptables -L 2>/dev/null | awk \'/^Chain FWX_LIMIT_/ {print $2}\'); do',
    '    iptables -D INPUT -p tcp -j "$CH" 2>/dev/null || true',
    '    iptables -D FORWARD -p tcp -j "$CH" 2>/dev/null || true',
    '    iptables -F "$CH" 2>/dev/null || true',
    '    iptables -X "$CH" 2>/dev/null || true',
    '    echo "[信息] 已清理连接限制链: $CH"',
    '  done',
    '',
    '  # 清理 nat 表中的 DNAT/MASQUERADE 规则',
    '  while iptables -t nat -S PREROUTING 2>/dev/null | grep -q "DNAT"; do',
    '    RULE=$(iptables -t nat -S PREROUTING 2>/dev/null | grep "DNAT" | head -1 | sed "s/^-A/-D/")',
    '    [ -z "$RULE" ] && break',
    '    iptables -t nat $RULE 2>/dev/null || break',
    '  done',
    '  while iptables -t nat -S POSTROUTING 2>/dev/null | grep -q "MASQUERADE"; do',
    '    RULE=$(iptables -t nat -S POSTROUTING 2>/dev/null | grep "MASQUERADE" | head -1 | sed "s/^-A/-D/")',
    '    [ -z "$RULE" ] && break',
    '    iptables -t nat $RULE 2>/dev/null || break',
    '  done',
    '  echo "[信息] iptables 规则已清理"',
    '',
    '  echo "[步骤 5/5] 清理日志和状态文件..."',
    '  rm -rf /var/log/forwardx-agent 2>/dev/null || true',
    '  rm -rf /var/lib/forwardx-agent 2>/dev/null || true',
    '  echo "[信息] 日志和状态文件已删除"',
    '',
    '  echo ""',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 卸载完成!"',
    '  echo "======================================"',
    '  echo ""',
    '  echo "  如需重新安装，请使用 install 命令"',
    '  echo "======================================"',
    '}',
    '',
    '# ============ 安装依赖 ============',
    '',
    'install_deps() {',
    '  echo "[步骤 1/6] 安装系统依赖..."',
    '  if command -v apt-get >/dev/null 2>&1; then',
    '    export DEBIAN_FRONTEND=noninteractive',
    '    apt-get update -qq && apt-get install -y -qq ca-certificates curl jq socat iptables nftables iproute2 coreutils systemd iperf3 >/dev/null 2>&1 || true',
    '    apt-get install -y -qq chrony >/dev/null 2>&1 || apt-get install -y -qq systemd-timesyncd >/dev/null 2>&1 || true',
    '  elif command -v dnf >/dev/null 2>&1; then',
    '    dnf install -y -q ca-certificates curl jq socat iptables nftables iproute coreutils systemd iperf3 >/dev/null 2>&1 || true',
    '    dnf install -y -q chrony >/dev/null 2>&1 || true',
    '  elif command -v yum >/dev/null 2>&1; then',
    '    yum install -y -q ca-certificates curl jq socat iptables nftables iproute coreutils systemd iperf3 >/dev/null 2>&1 || true',
    '    yum install -y -q chrony >/dev/null 2>&1 || true',
    '  elif command -v zypper >/dev/null 2>&1; then',
    '    zypper -n install ca-certificates curl jq socat iptables nftables iproute2 coreutils systemd iperf3 >/dev/null 2>&1 || true',
    '    zypper -n install chrony >/dev/null 2>&1 || true',
    '  elif command -v apk >/dev/null 2>&1; then',
    '    apk add --no-cache ca-certificates curl jq socat iptables nftables iproute2 coreutils openrc iperf3 >/dev/null 2>&1 || true',
    '    apk add --no-cache chrony >/dev/null 2>&1 || true',
    '  elif command -v pacman >/dev/null 2>&1; then',
    '    pacman -Sy --noconfirm ca-certificates curl jq socat iptables-nft nftables iproute2 coreutils iperf3 >/dev/null 2>&1 || pacman -Sy --noconfirm ca-certificates curl jq socat iptables nftables iproute2 coreutils iperf3 >/dev/null 2>&1 || true',
    '    pacman -Sy --noconfirm chrony >/dev/null 2>&1 || true',
    '  fi',
    '  # 验证关键依赖',
    '  for B in curl jq iptables iperf3; do',
    '    if ! command -v $B >/dev/null 2>&1; then',
    '      echo "[错误] 未能安装依赖: $B"',
    '      exit 1',
    '    fi',
    '  done',
    '  echo "[信息] 系统依赖就绪"',
    '}',
    '',
    'sync_system_time() {',
    '  echo "[信息] 同步系统时间（Agent 加密上报依赖主控/被控时间一致）..."',
    '  local SYNCED=0',
    '  if command -v timedatectl >/dev/null 2>&1; then',
    '    timedatectl set-ntp true >/dev/null 2>&1 || true',
    '  fi',
    '  if is_systemd_host; then',
    '    for SVC in chronyd chrony systemd-timesyncd; do',
    '      systemctl enable --now "$SVC" >/dev/null 2>&1 || systemctl restart "$SVC" >/dev/null 2>&1 || true',
    '    done',
    '  elif command -v rc-service >/dev/null 2>&1; then',
    '    rc-update add chronyd default >/dev/null 2>&1 || true',
    '    rc-service chronyd restart >/dev/null 2>&1 || true',
    '  fi',
    '  if command -v chronyc >/dev/null 2>&1; then',
    '    chronyc -a "burst 4/4" >/dev/null 2>&1 || true',
    '    if chronyc -a makestep >/dev/null 2>&1; then',
    '      SYNCED=1',
    '    elif chronyc tracking >/dev/null 2>&1; then',
    '      SYNCED=1',
    '    fi',
    '  fi',
    '  if [ "$SYNCED" != "1" ] && command -v timedatectl >/dev/null 2>&1; then',
    '    local I NTP_SYNCED',
    '    for I in 1 2 3 4 5 6 7 8 9 10; do',
    '      NTP_SYNCED="$(timedatectl show -p NTPSynchronized --value 2>/dev/null || true)"',
    '      if [ "$NTP_SYNCED" = "yes" ] || [ "$NTP_SYNCED" = "true" ]; then',
    '        SYNCED=1',
    '        break',
    '      fi',
    '      sleep 2',
    '    done',
    '  fi',
    '  if [ "$SYNCED" != "1" ] && command -v ntpd >/dev/null 2>&1; then',
    '    ntpd -q -p pool.ntp.org >/dev/null 2>&1 && SYNCED=1 || true',
    '  fi',
    '  if [ "$SYNCED" != "1" ] && command -v busybox >/dev/null 2>&1; then',
    '    busybox ntpd -q -p pool.ntp.org >/dev/null 2>&1 && SYNCED=1 || true',
    '  fi',
    '  echo "[信息] 当前系统时间: $(date -u "+%Y-%m-%d %H:%M:%S UTC" 2>/dev/null || date)"',
    '  if [ "$SYNCED" = "1" ]; then',
    '    echo "[信息] 系统时间同步已尝试完成"',
    '  else',
    '    echo "[警告] 未确认系统时间已同步；如果 Agent 上报 400/401，请先校准被控与主控时间后重试"',
    '  fi',
    '}',
    '',
    'install_realm() {',
    '  if command -v realm >/dev/null 2>&1; then',
    '    echo "[信息] realm 已安装"',
    '    return 0',
    '  fi',
    '  echo "[信息] 安装 realm..."',
    '  REALM_VERSION="v2.6.0"',
    '  ARCH=$(uname -m)',
    '  case "$ARCH" in',
    '    x86_64|amd64) REALM_ARCH="x86_64-unknown-linux-gnu" ;;',
    '    aarch64|arm64) REALM_ARCH="aarch64-unknown-linux-gnu" ;;',
    '    *) echo "[警告] 不支持的架构: $ARCH, 跳过 realm"; return 1 ;;',
    '  esac',
    '  TMP=$(mktemp -d)',
    '  URL="https://github.com/zhboner/realm/releases/download/$REALM_VERSION/realm-$REALM_ARCH.tar.gz"',
    '  URL="$(github_url "$URL")"',
    "  if curl -fsSL --connect-timeout \"$FORWARDX_CURL_CONNECT_TIMEOUT\" --speed-limit \"$FORWARDX_CURL_LOW_SPEED_LIMIT\" --speed-time \"$FORWARDX_CURL_ASSET_LOW_SPEED_TIME\" \"$URL\" -o \"$TMP/realm.tgz\"; then",
    '    tar -xzf "$TMP/realm.tgz" -C "$TMP" 2>/dev/null || true',
    '    REALM_BIN=$(find "$TMP" -type f -name realm | head -n1)',
    '    if [ -n "$REALM_BIN" ]; then',
    '      install -m 0755 "$REALM_BIN" /usr/local/bin/realm',
    '      rm -rf "$TMP"',
    '      echo "[信息] realm 安装完成"',
    '      return 0',
    '    fi',
    '  fi',
    '  rm -rf "$TMP"',
    '  echo "[警告] realm 安装失败，realm 转发方式将不可用"',
    '  return 1',
    '}',
    '',
    'runtime_self_check() {',
    '  local BIN="$1"',
    '  [ -x "$BIN" ] || return 1',
    '  local TARGET_VERSION OUT HELP',
    '  TARGET_VERSION="${GOST_VERSION:-3.2.6}"',
    '  TARGET_VERSION="${TARGET_VERSION#v}"',
    '  OUT="$("$BIN" -V 2>&1 || "$BIN" --version 2>&1 || true)"',
    '  HELP="$("$BIN" -h 2>&1 || true)"',
    '  echo "$HELP" | grep -q -- "-L" || return 1',
    '  echo "$HELP" | grep -q -- "-F" || return 1',
    '  printf "%s\\n%s\\n" "$OUT" "$HELP" | grep -q "$TARGET_VERSION" || return 1',
    '}',
    '',
    "install_runtime_from_panel() {",
    "  local GO_ARCH VERSION URL SEEN=\"\"",
    "  GO_ARCH=$(detect_arch)",
    "  if [ -z \"$GO_ARCH\" ]; then",
    "    echo \"[警告] 不支持的 CPU 架构: $(uname -m)，跳过面板 gost runtime\"",
    "    return 1",
    "  fi",
    "  for VERSION in \"${RELEASE_VERSION:-}\" \"${DOWNLOADED_RELEASE_VERSION:-}\" \"${FALLBACK_RELEASE_VERSION:-}\"; do",
    "    VERSION=\"${VERSION#v}\"",
    "    [ -n \"$VERSION\" ] || continue",
    "    case \" $SEEN \" in *\" $VERSION \"*) continue ;; esac",
    "    SEEN=\"$SEEN $VERSION\"",
    "    URL=\"$(panel_asset_url \"$VERSION\" \"forwardx-runtime-linux-${GO_ARCH}\")\"",
    "    if download_panel_binary \"$URL\" \"$RUNTIME_BIN\" \"gost runtime\"; then",
    "      if runtime_self_check \"$RUNTIME_BIN\"; then",
    "        echo \"[信息] gost runtime 已从面板安装: v${VERSION} -> $RUNTIME_BIN\"",
    "        return 0",
    "      fi",
    "      echo \"[警告] 面板 gost runtime 自检失败: v${VERSION}\"",
    "      rm -f \"$RUNTIME_BIN\"",
    "    fi",
    "  done",
    "  return 1",
    "}",
    "",
    "install_runtime_from_github() {",
    "  GOST_VERSION=\"${GOST_VERSION:-3.2.6}\"",
    "  GOST_VERSION=\"${GOST_VERSION#v}\"",
    "  echo \"[信息] 正在从 GitHub 安装 gost...\"",
    "  ARCH=$(uname -m)",
    "  case \"$ARCH\" in",
    "    x86_64|amd64) GOST_ARCHS=\"amd64v1 amd64 amd64v2 amd64v3\" ;;",
    "    aarch64|arm64) GOST_ARCHS=\"arm64\" ;;",
    "    *) echo \"[警告] 不支持的 CPU 架构: $ARCH，跳过 gost 安装\"; return 1 ;;",
    "  esac",
    "  TMP=$(mktemp -d)",
    "  for GOST_ARCH in $GOST_ARCHS; do",
    "    URL=\"https://github.com/go-gost/gost/releases/download/v${GOST_VERSION}/gost_${GOST_VERSION}_linux_${GOST_ARCH}.tar.gz\"",
    "    URL=\"$(github_url \"$URL\")\"",
    "    HTTP_STATUS=\"000\"",
    "    CURL_RC=0",
    "    rm -f \"$TMP/gost.tgz\" \"$TMP/gost.status\"",
    "    echo \"[信息] 尝试安装 gost 架构包: $GOST_ARCH\"",
    "    curl -fsSL --connect-timeout \"$FORWARDX_CURL_CONNECT_TIMEOUT\" --speed-limit \"$FORWARDX_CURL_LOW_SPEED_LIMIT\" --speed-time \"$FORWARDX_CURL_ASSET_LOW_SPEED_TIME\" -w \"%{http_code}\" \"$URL\" -o \"$TMP/gost.tgz\" > \"$TMP/gost.status\" 2>/dev/null || CURL_RC=$?",
    "    if [ -s \"$TMP/gost.status\" ]; then",
    "      HTTP_STATUS=\"$(cat \"$TMP/gost.status\" 2>/dev/null || printf \"000\")\"",
    "    fi",
    "    if [ \"$CURL_RC\" = \"0\" ] && [ -s \"$TMP/gost.tgz\" ]; then",
    "      if tar -xzf \"$TMP/gost.tgz\" -C \"$TMP\" && \\",
    "        GOST_BIN=$(find \"$TMP\" -type f -name gost | head -n1) && \\",
    "        [ -n \"$GOST_BIN\" ] && install -m 0755 \"$GOST_BIN\" \"$RUNTIME_BIN\" && \\",
    "        runtime_self_check \"$RUNTIME_BIN\"; then",
    "        rm -rf \"$TMP\" && echo \"[信息] gost 安装完成: $GOST_ARCH -> $RUNTIME_BIN\" && return 0",
    "      fi",
    "      echo \"[警告] gost 架构包 $GOST_ARCH 无法使用，尝试下一个候选\"",
    "    elif [ \"$HTTP_STATUS\" = \"404\" ]; then",
    "      echo \"[信息] gost 架构包 $GOST_ARCH 不存在，尝试下一个候选\"",
    "    else",
    "      echo \"[警告] gost 架构包 $GOST_ARCH 下载失败（HTTP=${HTTP_STATUS}, 退出码=${CURL_RC}），尝试下一个候选\"",
    "    fi",
    "  done",
    "  rm -rf \"$TMP\"",
    "  return 1",
    "}",
    "",
    "install_runtime() {",
    "  GOST_VERSION=\"${GOST_VERSION:-3.2.6}\"",
    "  GOST_VERSION=\"${GOST_VERSION#v}\"",
    "  if [ -e \"$RUNTIME_BIN\" ]; then",
    "    chmod 0755 \"$RUNTIME_BIN\" 2>/dev/null || true",
    "    if runtime_self_check \"$RUNTIME_BIN\"; then",
    "      echo \"[信息] gost runtime 已安装且版本匹配: $RUNTIME_BIN\"",
    "      return 0",
    "    fi",
    "    echo \"[警告] 已有 gost runtime 版本不匹配或不可用，正在重新安装: $RUNTIME_BIN\"",
    "    rm -f \"$RUNTIME_BIN\"",
    "  fi",
    "  for BIN in /usr/local/bin/gost \"$(command -v gost 2>/dev/null || true)\"; do",
    "    [ -n \"$BIN\" ] || continue",
    "    if runtime_self_check \"$BIN\"; then",
    "      install -m 0755 \"$BIN\" \"$RUNTIME_BIN\" && echo \"[信息] gost runtime 已从现有 gost 复制: $RUNTIME_BIN\" && return 0",
    "    fi",
    "  done",
    "  if command -v gost >/dev/null 2>&1; then",
    "    echo \"[警告] 已安装的 gost 与当前 CPU 不兼容或版本不匹配，正在重新安装\"",
    "  fi",
    "  if is_enabled_value \"${FORWARDX_AGENT_PANEL_FIRST:-}\"; then",
    "    if install_runtime_from_panel; then",
    "      return 0",
    "    fi",
    "    echo \"[信息] 面板 gost runtime 不可用，尝试从 GitHub 安装...\"",
    "    if install_runtime_from_github; then",
    "      return 0",
    "    fi",
    "  else",
    "    if install_runtime_from_github; then",
    "      return 0",
    "    fi",
    "    echo \"[信息] GitHub gost runtime 下载失败，回退到面板安装...\"",
    "    if install_runtime_from_panel; then",
    "      return 0",
    "    fi",
    "  fi",
    "  echo \"[警告] gost 安装失败，gost 转发方式将不可用\"",
    "  return 1",
    "}",
    "",
    'install_go_agent() {',
    '  GO_ARCH=$(detect_arch)',
    '  if [ -z "$GO_ARCH" ]; then',
    '    echo "[错误] 不支持的 CPU 架构: $(uname -m)"',
    '    return 1',
    '  fi',
    '',
    '  echo "[步骤 3/6] 安装 Go Agent（Release v${RELEASE_VERSION}）..."',
    '  DOWNLOADED_RELEASE_VERSION=""',
    '  if ! download_release_binary "forwardx-agent-linux-${GO_ARCH}" "$GO_AGENT_BIN" "Go Agent" "1"; then',
    '    echo "[错误] Go Agent 二进制下载失败，请检查网络或 Release 资产是否已构建完成"',
    '    return 1',
    '  fi',
    '',
    '  echo "[步骤 4/6] 安装 ForwardX Tunnel Runtime..."',
    '  FXP_RELEASE_VERSION="${DOWNLOADED_RELEASE_VERSION:-$RELEASE_VERSION}"',
    '  RELEASE_VERSION="$FXP_RELEASE_VERSION" download_release_binary "forwardx-fxp-linux-${GO_ARCH}" "$FXP_BIN" "ForwardX FXP" "0" || \\',
    '    echo "[警告] FXP 安装失败，加密隧道功能将不可用（iptables/realm/socat/gost 转发不受影响）"',
    '',
    '  return 0',
    '}',
    '',
    'register_agent_once() {',
    '  echo "[步骤 6/6] 注册到面板..."',
    '  local OUT RC',
    '  if OUT=$("$GO_AGENT_BIN" -config "$CONFIG_DIR/config.json" -register 2>&1); then',
    '    [ -n "$OUT" ] && printf "%s\\n" "$OUT"',
    '    echo "[信息] Agent 已通过加密通道注册到面板"',
    '    return 0',
    '  else',
    '    RC=$?',
    '    echo "[错误] Agent 注册失败（退出码: $RC）"',
    '    [ -n "$OUT" ] && printf "%s\\n" "$OUT"',
    '    echo "[提示] 请检查 Token、面板地址、服务器时间，以及面板是否已更新到支持加密通讯的版本"',
    '    return "$RC"',
    '  fi',
    '}',
    '',
    'start_agent_service_systemd_unused() {',
    '  if ! systemctl restart "$SERVICE_NAME"; then',
    '    echo "[错误] systemd 服务启动失败"',
    '    systemctl status "$SERVICE_NAME" --no-pager -l 2>/dev/null || true',
    '    return 1',
    '  fi',
    '  sleep 1',
    '  if ! systemctl is-active --quiet "$SERVICE_NAME"; then',
    '    echo "[错误] systemd 服务未保持运行"',
    '    systemctl status "$SERVICE_NAME" --no-pager -l 2>/dev/null || true',
    '    journalctl -u "$SERVICE_NAME" -n 50 --no-pager 2>/dev/null || true',
    '    return 1',
    '  fi',
    '  echo "[信息] systemd 服务已启动"',
    '}',
    '',
    '# ============ 安装 ============',
    '',
    'do_install() {',
    '  if [ "$(id -u)" != "0" ]; then',
    '    echo "[错误] 请使用 root 权限运行此脚本"',
    '    exit 1',
    '  fi',
    '',
    '  resolve_token',
    '',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 安装程序"',
    '  echo "======================================"',
    '  echo "面板地址: $PANEL_URL"',
    '  echo "Token: ${AGENT_TOKEN:0:8}***"',
    '  echo ""',
    '',
    '  # 安装系统依赖',
    '  install_deps',
    '  sync_system_time',
    '',
    '  # 启用内核转发和 conntrack 计数器',
    '  echo "[步骤 2/6] 配置内核参数..."',
    '  sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1 || true',
    '  sysctl -w net.netfilter.nf_conntrack_acct=1 >/dev/null 2>&1 || true',
    '  if ! grep -qE "^\\s*net\\.ipv4\\.ip_forward\\s*=\\s*1" /etc/sysctl.conf 2>/dev/null; then',
    '    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf',
    '  fi',
    '  if ! grep -qE "^\\s*net\\.netfilter\\.nf_conntrack_acct\\s*=\\s*1" /etc/sysctl.conf 2>/dev/null; then',
    '    echo "net.netfilter.nf_conntrack_acct=1" >> /etc/sysctl.conf',
    '  fi',
    '  sysctl -p >/dev/null 2>&1 || true',
    '  echo "[信息] 内核参数就绪"',
    '',
    '  # 安装 Go Agent 二进制',
    '  if ! install_go_agent; then',
    '    echo "[错误] Go Agent 安装失败，安装中止"',
    '    exit 1',
    '  fi',
    '',
    '  # 安装可选转发工具',
    '  install_realm || true',
    '  if ! install_runtime; then',
    '    echo "[错误] gost runtime 安装失败，安装中止"',
    '    exit 1',
    '  fi',
    '',
    '  # 创建配置',
    '  echo "[步骤 5/6] 配置 Agent..."',
    '  mkdir -p "$CONFIG_DIR"',
    '  cat > "$CONFIG_DIR/config.json" << EOF',
    '{',
    '  "panelUrl": "$PANEL_URL",',
    '  "token": "$AGENT_TOKEN",',
    '  "interval": 30',
    '}',
    'EOF',
    '  chmod 600 "$CONFIG_DIR/config.json" 2>/dev/null || true',
    '  echo "[信息] 配置文件已写入: $CONFIG_DIR/config.json"',
    '',
    '  # 安装系统服务',
    '  write_agent_service',
    '',
    '  register_agent_once',
    '  start_agent_service',
    '',
    '  echo ""',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 安装完成!"',
    '  echo "======================================"',
    '  echo "  Go Agent:  $GO_AGENT_BIN"',
    '  echo "  配置文件:  $CONFIG_DIR/config.json"',
    '  echo "  服务名称:  $SERVICE_NAME"',
    '  print_agent_service_hints',
    '  echo "  卸载命令:  curl -sL $PANEL_URL/api/agent/install.sh | bash -s -- uninstall"',
    '  echo "======================================"',
    '}',
    '',
    '# ============ 升级 ============',
    '',
    'do_upgrade() {',
    '  if [ "$(id -u)" != "0" ]; then',
    '    echo "[错误] 请使用 root 权限运行此脚本"',
    '    exit 1',
    '  fi',
    '',
    '  # 尝试从现有配置文件读取',
    '  if [ -f "$CONFIG_DIR/config.json" ]; then',
    '    EXISTING_PANEL_URL=$(jq -r ".panelUrl // empty" "$CONFIG_DIR/config.json" 2>/dev/null || true)',
    '    EXISTING_TOKEN=$(jq -r ".token // empty" "$CONFIG_DIR/config.json" 2>/dev/null || true)',
    '  fi',
    '',
    '  PANEL_URL="${PANEL_URL:-${EXISTING_PANEL_URL:-}}"',
    '  if [ -n "$TOKEN" ]; then',
    '    AGENT_TOKEN="$TOKEN"',
    '  else',
    '    AGENT_TOKEN="${EXISTING_TOKEN:-}"',
    '  fi',
    '',
    '  if [ -z "$PANEL_URL" ]; then',
    '    echo "[错误] 未找到面板地址"',
    '    exit 1',
    '  fi',
    '',
    '  echo "======================================"',
    '  echo "  ForwardX Agent 升级程序"',
    '  echo "======================================"',
    '  echo "面板地址: $PANEL_URL"',
    '  echo ""',
    '',
    '  # 下载并替换 Go Agent 二进制',
    '  GO_ARCH=$(detect_arch)',
    '  if [ -z "$GO_ARCH" ]; then',
    '    echo "[错误] 不支持的 CPU 架构"',
    '    exit 1',
    '  fi',
    '',
    '  echo "[信息] 升级 Go Agent（Release v${RELEASE_VERSION}）..."',
    '  DOWNLOADED_RELEASE_VERSION=""',
    '  if download_release_binary "forwardx-agent-linux-${GO_ARCH}" "$GO_AGENT_BIN" "Go Agent" "0"; then',
    '    FXP_RELEASE_VERSION="${DOWNLOADED_RELEASE_VERSION:-$RELEASE_VERSION}"',
    '    RELEASE_VERSION="$FXP_RELEASE_VERSION" download_release_binary "forwardx-fxp-linux-${GO_ARCH}" "$FXP_BIN" "ForwardX FXP" "0" || true',
    '    install_deps',
    '    sync_system_time',
    '    if ! install_runtime; then',
    '      echo "[错误] gost runtime 安装失败，升级中止"',
    '      return 1',
    '    fi',
    '',
    '    # 更新配置中的 token（如有提供）',
    '    if [ -n "$AGENT_TOKEN" ] && [ -f "$CONFIG_DIR/config.json" ]; then',
    '      jq --arg t "$AGENT_TOKEN" \'.token = $t\' "$CONFIG_DIR/config.json" > "$CONFIG_DIR/config.json.tmp" && \\',
    '        mv "$CONFIG_DIR/config.json.tmp" "$CONFIG_DIR/config.json"',
    '    fi',
    '',
    '    # 重启服务',
    '    start_agent_service',
    '    echo ""',
    '    echo "======================================"',
    '    echo "  ForwardX Agent 升级完成!"',
    '    echo "======================================"',
    '  else',
    '    echo "[错误] 升级失败"',
    '    exit 1',
    '  fi',
    '}',
    '',
    '# ============ 入口 ============',
    '',
    'case "$ACTION" in',
    '  install)',
    '    do_install',
    '    ;;',
    '  upgrade|update)',
    '    do_upgrade',
    '    ;;',
    '  uninstall|remove|delete)',
    '    do_uninstall',
    '    ;;',
    '  *)',
    '    show_help',
    '    [ -n "$ACTION" ] && echo "[提示] 未知操作: $ACTION"',
    '    exit 1',
    '    ;;',
    'esac',
    'exit 0',
  ];
  return lines.join('\n') + '\n';
}
