import assert from "node:assert/strict";
import * as runtime from "../dbRuntime";
import { ensureDatabaseSchema } from "../dbSchema";
import * as db from "../db";
import { preparePanelCall, executePanelCall, queryPanelCall, PanelPreflightError } from "./panelTools";

await runtime.connectDatabase({ type: "sqlite", sqlite: { path: process.env.FORWARDX_TEST_DB! } });
try {
  await ensureDatabaseSchema();
  await runtime.executeRaw('INSERT INTO users (id,username,password,name,role,"accountEnabled","canAddRules","manualCanAddRules") VALUES (1,?,?,?,\'admin\',1,1,1)', ["admin", "private-password", "管理员"]);
  await runtime.executeRaw('INSERT INTO users (id,username,password,name,role,"accountEnabled","expiresAt") VALUES (2,?,?,?,\'user\',1,?)', ["customer", "secret-user-password", "客户", Math.floor(Date.now()/1000) + 2 * 86400]);
  await runtime.executeRaw('INSERT INTO hosts (id,name,ip,"userId","agentToken","stoppedAt") VALUES (1,?,?,1,?,?)', ["香港", "192.0.2.1", "private-agent-token", Math.floor(Date.now()/1000) + 86400]);
  await runtime.executeRaw('INSERT INTO hosts (id,name,ip,"userId") VALUES (2,?,?,1)', ["东京", "192.0.2.2"]);
  await db.setSettings({ pluginsEnabled: "false", emailPassword: "secret-smtp-password", deepseekApiKey: "private-api-key" });
  const resources = async (kind: "rules" | "hosts") => kind === "hosts" ? await db.getHosts() : [{ id: 9, name: "测试规则", userId: 2 }];
  const query = await queryPanelCall(1, "settings.read", { keyword: "插件" }, resources);
  assert.equal(query.items[0].value, false);
  assert.doesNotMatch(JSON.stringify(query), /private-|secret-/);
  await assert.rejects(queryPanelCall(2, "settings.read", {}, resources), /管理员/);
  await assert.rejects(queryPanelCall(1, "settings.set", { key: "pluginsEnabled", value: true }, resources), /类型不匹配/);
  const setting = await preparePanelCall(1, "settings.set", { key: "pluginsEnabled", value: true });
  assert.match(setting.preview[0], /关闭.*开启/);
  assert.equal(await db.getSetting("pluginsEnabled"), "false"); // preview is read-only
  await executePanelCall(1, setting);
  assert.equal(await db.getSetting("pluginsEnabled"), "true");
  const stale = await preparePanelCall(1, "settings.set", { key: "pluginsEnabled", value: false });
  await db.setSetting("pluginsEnabled", "false");
  await assert.rejects(executePanelCall(1, stale), PanelPreflightError);
  await db.setSetting("forwardProtocols", JSON.stringify({ gost: false, realm: false }));
  await executePanelCall(1, await preparePanelCall(1, "settings.set", { key: "protocol.gost", value: true }));
  assert.equal(JSON.parse((await db.getSetting("forwardProtocols"))!).realm, false);
  assert.equal(JSON.parse((await db.getSetting("forwardProtocols"))!).gost, true);
  await executePanelCall(1, await preparePanelCall(1, "settings.set", { key: "menu.dashboard", value: false }));
  assert.equal(JSON.parse((await db.getSetting("sidebarMenu"))!).users, true);
  assert.equal(JSON.parse((await db.getSetting("sidebarMenu"))!).dashboard, false);
  const expiry = await queryPanelCall(1, "expiry.list", { resource: "rules", days: 3 }, resources);
  assert.equal(expiry.items[0].id, 9);
  assert.match(expiry.label, /所属账户/);
  assert.equal((await queryPanelCall(1, "expiry.list", { resource: "hosts", days: 3 }, resources)).items[0].id, 1);
  await executePanelCall(1, await preparePanelCall(1, "hosts.update", { id: 1, renewalReminderDays: 3, trafficMeasureMode: "outbound" }));
  assert.equal((await db.getHostById(1))!.renewalReminderDays, 3);
  assert.equal((await db.getHostById(1))!.trafficMeasureMode, "outbound");
  await db.setUserHostPermissions(2, [1]);
  await executePanelCall(1, await preparePanelCall(1, "users.permissions_change", { userId: 2, resource: "host", operation: "add", resourceIds: [2] }));
  assert.deepEqual((await db.getUserAllowedHostIds(2)).sort(), [1,2]);
  await executePanelCall(1, await preparePanelCall(1, "users.permissions_change", { userId: 2, resource: "host", operation: "remove", resourceIds: [2] }));
  assert.deepEqual(await db.getUserAllowedHostIds(2), [1]);
  const group = await executePanelCall(1, await preparePanelCall(1, "groups.create", { name: "端口链", groupMode: "port", groupType: "host", members: [{ memberType: "host", hostId: 1 }], forwardType: "gost" }));
  const groupId = group.result.id;
  await executePanelCall(1, await preparePanelCall(1, "groups.update", { id: groupId, name: "新名称", proxyProtocolSend: false }));
  const updatedGroup: any = await db.getForwardGroupById(groupId);
  assert.equal(updatedGroup.name, "新名称");
  assert.equal(updatedGroup.members[0].hostId, 1);
  await executePanelCall(1, await preparePanelCall(1, "groups.toggle", { id: groupId, isEnabled: false }));
  assert.equal((await db.getForwardGroupById(groupId))!.isEnabled, false);
  await executePanelCall(1, await preparePanelCall(1, "groups.toggle", { id: groupId, isEnabled: true }));
  await db.setSetting("forwardProtocols", "{}");
  const rule = await executePanelCall(1, await preparePanelCall(1, "rules.create", { name: "AI端口规则", forwardGroupId: groupId, sourcePort: 23001, targetIp: "192.0.2.99", targetPort: 443 }));
  assert.ok(rule.result.id);
  await executePanelCall(1, await preparePanelCall(1, "rules.update", { id: rule.result.id, targetPort: 8443 }));
  assert.equal((await db.getForwardRuleById(rule.result.id))!.targetPort, 8443);
  await assert.rejects(preparePanelCall(2, "rules.update", { id: rule.result.id, targetPort: 80 }), /无权/);
  await executePanelCall(1, await preparePanelCall(1, "users.limits", { userId: 2, maxRules: 15 }));
  assert.equal((await db.getUserById(2))!.manualMaxRules, 15);
  const plan = await executePanelCall(1, await preparePanelCall(1, "plans.create", { name: "基础套餐", priceCents: 1000, durationDays: 30, hostIds: [1], tunnelIds: [], forwardGroupIds: [] }));
  await executePanelCall(1, await preparePanelCall(1, "plans.update", { id: plan.result.id, priceCents: 1200, syncExistingSubscribers: false }));
  const updatedPlan = await db.getSubscriptionPlanById(plan.result.id);
  assert.equal(updatedPlan!.priceCents, 1200);
  assert.deepEqual(updatedPlan!.hostIds, [1]);
  await executePanelCall(1, await preparePanelCall(1, "subscriptions.assign", { userId: 2, planId: plan.result.id }));
  const subscriptions = await queryPanelCall(1, "subscriptions.list", { userId: 2 }, resources);
  assert.equal(subscriptions.total, 1);
  assert.equal((await queryPanelCall(1, "subscriptions.list", { scope: "self" }, resources)).total, 0);
  const subscriptionId = subscriptions.items[0].id;
  await executePanelCall(1, await preparePanelCall(1, "subscriptions.extend", { id: subscriptionId, days: 1 }));
  await executePanelCall(1, await preparePanelCall(1, "subscriptions.cancel", { id: subscriptionId }));
  const tunnel = await executePanelCall(1, await preparePanelCall(1, "tunnels.create", { name: "AI隧道", mode: "forwardx", entryHostId: 1, exitHostId: 2, listenPort: 23002, forwardxVersion: "v1" }));
  assert.ok(tunnel.result.id);
  assert.doesNotMatch(JSON.stringify(tunnel), /secret|certKeyPem/);
  await executePanelCall(1, await preparePanelCall(1, "tunnels.update", { id: tunnel.result.id, rateLimitMbps: 100 }));
  assert.equal((await db.getTunnelById(tunnel.result.id))!.rateLimitMbps, 100);
  const downgrade = await preparePanelCall(1, "settings.set", { key: "pluginsEnabled", value: true });
  await runtime.executeRaw("UPDATE users SET role='user' WHERE id=1");
  await assert.rejects(executePanelCall(1, downgrade), /管理员/);
  assert.equal(await db.getSetting("pluginsEnabled"), "false");
} finally { await runtime.closeDatabase(); }
